/* accesoH.h
   Generated by gSOAP 2.8.21 from acceso.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef accesoH_H
#define accesoH_H
#include "accesoStub.h"

namespace acceso {
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 acceso_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 acceso_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 acceso_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso_byte
#define SOAP_TYPE_acceso_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_byte(soap, data),0) || acceso::soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_int
#define SOAP_TYPE_acceso_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_int(soap, data),0) || acceso::soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_unsignedByte
#define SOAP_TYPE_acceso_unsignedByte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#ifndef soap_write_unsignedByte
#define soap_write_unsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_unsignedByte(soap, data),0) || acceso::soap_put_unsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef soap_read_unsignedByte
#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_unsignedInt
#define SOAP_TYPE_acceso_unsignedInt (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_unsignedInt(soap, data),0) || acceso::soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_time
#define SOAP_TYPE_acceso_time (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);

#ifndef soap_write_time
#define soap_write_time(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_time(soap, data),0) || acceso::soap_put_time(soap, data, "dateTime", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);

#ifndef soap_read_time
#define soap_read_time(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_time(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_std__string
#define SOAP_TYPE_acceso_std__string (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_std__string(soap, data),0) || soap_put_std__string(soap, data, "string", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1) { return soap_instantiate_std__string(soap, n, NULL, NULL, NULL); }

inline std::string * soap_new_req_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline std::string * soap_new_set_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline void soap_delete_std__string(struct soap *soap, std::string *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse
#define SOAP_TYPE_acceso_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(struct soap*, const char*, int, const ns1__Modulo_USCOREAcceso_USCOREPuertaResponse *, const char*);
SOAP_FMAC3 ns1__Modulo_USCOREAcceso_USCOREPuertaResponse * SOAP_FMAC4 soap_in_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(struct soap*, const char*, ns1__Modulo_USCOREAcceso_USCOREPuertaResponse *, const char*);

#ifndef soap_write_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse
#define soap_write_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:Modulo_Acceso_PuertaResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__Modulo_USCOREAcceso_USCOREPuertaResponse * SOAP_FMAC4 soap_get_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(struct soap*, ns1__Modulo_USCOREAcceso_USCOREPuertaResponse *, const char*, const char*);

#ifndef soap_read_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse
#define soap_read_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__Modulo_USCOREAcceso_USCOREPuertaResponse * SOAP_FMAC2 soap_instantiate_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__Modulo_USCOREAcceso_USCOREPuertaResponse * soap_new_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(soap, n, NULL, NULL, NULL); }

inline ns1__Modulo_USCOREAcceso_USCOREPuertaResponse * soap_new_req_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(struct soap *soap) { ns1__Modulo_USCOREAcceso_USCOREPuertaResponse *_p = soap_instantiate_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__Modulo_USCOREAcceso_USCOREPuertaResponse * soap_new_set_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(struct soap *soap, std::string *return_) { ns1__Modulo_USCOREAcceso_USCOREPuertaResponse *_p = soap_instantiate_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__Modulo_USCOREAcceso_USCOREPuertaResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(struct soap *soap, ns1__Modulo_USCOREAcceso_USCOREPuertaResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Modulo_USCOREAcceso_USCOREPuertaResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso_ns1__Modulo_USCOREAcceso_USCOREPuerta
#define SOAP_TYPE_acceso_ns1__Modulo_USCOREAcceso_USCOREPuerta (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, const char*, int, const ns1__Modulo_USCOREAcceso_USCOREPuerta *, const char*);
SOAP_FMAC3 ns1__Modulo_USCOREAcceso_USCOREPuerta * SOAP_FMAC4 soap_in_ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, const char*, ns1__Modulo_USCOREAcceso_USCOREPuerta *, const char*);

#ifndef soap_write_ns1__Modulo_USCOREAcceso_USCOREPuerta
#define soap_write_ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:Modulo_Acceso_Puerta", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__Modulo_USCOREAcceso_USCOREPuerta * SOAP_FMAC4 soap_get_ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, ns1__Modulo_USCOREAcceso_USCOREPuerta *, const char*, const char*);

#ifndef soap_read_ns1__Modulo_USCOREAcceso_USCOREPuerta
#define soap_read_ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__Modulo_USCOREAcceso_USCOREPuerta * SOAP_FMAC2 soap_instantiate_ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, int, const char*, const char*, size_t*);

inline ns1__Modulo_USCOREAcceso_USCOREPuerta * soap_new_ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap *soap, int n = -1) { return soap_instantiate_ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, n, NULL, NULL, NULL); }

inline ns1__Modulo_USCOREAcceso_USCOREPuerta * soap_new_req_ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap *soap, int tipomarca) { ns1__Modulo_USCOREAcceso_USCOREPuerta *_p = soap_instantiate_ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__Modulo_USCOREAcceso_USCOREPuerta::tipomarca = tipomarca; } return _p; }

inline ns1__Modulo_USCOREAcceso_USCOREPuerta * soap_new_set_ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap *soap, std::string *rut, std::string *dato_USCORErecibido, time_t *fecha, std::string *numerodispositivo, int tipomarca, xsd__base64Binary *foto) { ns1__Modulo_USCOREAcceso_USCOREPuerta *_p = soap_instantiate_ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__Modulo_USCOREAcceso_USCOREPuerta::rut = rut; _p->ns1__Modulo_USCOREAcceso_USCOREPuerta::dato_USCORErecibido = dato_USCORErecibido; _p->ns1__Modulo_USCOREAcceso_USCOREPuerta::fecha = fecha; _p->ns1__Modulo_USCOREAcceso_USCOREPuerta::numerodispositivo = numerodispositivo; _p->ns1__Modulo_USCOREAcceso_USCOREPuerta::tipomarca = tipomarca; _p->ns1__Modulo_USCOREAcceso_USCOREPuerta::foto = foto; } return _p; }

inline void soap_delete_ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap *soap, ns1__Modulo_USCOREAcceso_USCOREPuerta *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso_ns1__Modulo_USCOREobtener_USCOREhoraResponse
#define SOAP_TYPE_acceso_ns1__Modulo_USCOREobtener_USCOREhoraResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Modulo_USCOREobtener_USCOREhoraResponse(struct soap*, const char*, int, const ns1__Modulo_USCOREobtener_USCOREhoraResponse *, const char*);
SOAP_FMAC3 ns1__Modulo_USCOREobtener_USCOREhoraResponse * SOAP_FMAC4 soap_in_ns1__Modulo_USCOREobtener_USCOREhoraResponse(struct soap*, const char*, ns1__Modulo_USCOREobtener_USCOREhoraResponse *, const char*);

#ifndef soap_write_ns1__Modulo_USCOREobtener_USCOREhoraResponse
#define soap_write_ns1__Modulo_USCOREobtener_USCOREhoraResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:Modulo_obtener_horaResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__Modulo_USCOREobtener_USCOREhoraResponse * SOAP_FMAC4 soap_get_ns1__Modulo_USCOREobtener_USCOREhoraResponse(struct soap*, ns1__Modulo_USCOREobtener_USCOREhoraResponse *, const char*, const char*);

#ifndef soap_read_ns1__Modulo_USCOREobtener_USCOREhoraResponse
#define soap_read_ns1__Modulo_USCOREobtener_USCOREhoraResponse(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_ns1__Modulo_USCOREobtener_USCOREhoraResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__Modulo_USCOREobtener_USCOREhoraResponse * SOAP_FMAC2 soap_instantiate_ns1__Modulo_USCOREobtener_USCOREhoraResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__Modulo_USCOREobtener_USCOREhoraResponse * soap_new_ns1__Modulo_USCOREobtener_USCOREhoraResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__Modulo_USCOREobtener_USCOREhoraResponse(soap, n, NULL, NULL, NULL); }

inline ns1__Modulo_USCOREobtener_USCOREhoraResponse * soap_new_req_ns1__Modulo_USCOREobtener_USCOREhoraResponse(struct soap *soap) { ns1__Modulo_USCOREobtener_USCOREhoraResponse *_p = soap_instantiate_ns1__Modulo_USCOREobtener_USCOREhoraResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__Modulo_USCOREobtener_USCOREhoraResponse * soap_new_set_ns1__Modulo_USCOREobtener_USCOREhoraResponse(struct soap *soap, time_t *return_) { ns1__Modulo_USCOREobtener_USCOREhoraResponse *_p = soap_instantiate_ns1__Modulo_USCOREobtener_USCOREhoraResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__Modulo_USCOREobtener_USCOREhoraResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__Modulo_USCOREobtener_USCOREhoraResponse(struct soap *soap, ns1__Modulo_USCOREobtener_USCOREhoraResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Modulo_USCOREobtener_USCOREhoraResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso_ns1__Modulo_USCOREobtener_USCOREhora
#define SOAP_TYPE_acceso_ns1__Modulo_USCOREobtener_USCOREhora (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, const char*, int, const ns1__Modulo_USCOREobtener_USCOREhora *, const char*);
SOAP_FMAC3 ns1__Modulo_USCOREobtener_USCOREhora * SOAP_FMAC4 soap_in_ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, const char*, ns1__Modulo_USCOREobtener_USCOREhora *, const char*);

#ifndef soap_write_ns1__Modulo_USCOREobtener_USCOREhora
#define soap_write_ns1__Modulo_USCOREobtener_USCOREhora(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:Modulo_obtener_hora", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__Modulo_USCOREobtener_USCOREhora * SOAP_FMAC4 soap_get_ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, ns1__Modulo_USCOREobtener_USCOREhora *, const char*, const char*);

#ifndef soap_read_ns1__Modulo_USCOREobtener_USCOREhora
#define soap_read_ns1__Modulo_USCOREobtener_USCOREhora(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_ns1__Modulo_USCOREobtener_USCOREhora(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__Modulo_USCOREobtener_USCOREhora * SOAP_FMAC2 soap_instantiate_ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, int, const char*, const char*, size_t*);

inline ns1__Modulo_USCOREobtener_USCOREhora * soap_new_ns1__Modulo_USCOREobtener_USCOREhora(struct soap *soap, int n = -1) { return soap_instantiate_ns1__Modulo_USCOREobtener_USCOREhora(soap, n, NULL, NULL, NULL); }

inline ns1__Modulo_USCOREobtener_USCOREhora * soap_new_req_ns1__Modulo_USCOREobtener_USCOREhora(struct soap *soap) { ns1__Modulo_USCOREobtener_USCOREhora *_p = soap_instantiate_ns1__Modulo_USCOREobtener_USCOREhora(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__Modulo_USCOREobtener_USCOREhora * soap_new_set_ns1__Modulo_USCOREobtener_USCOREhora(struct soap *soap) { ns1__Modulo_USCOREobtener_USCOREhora *_p = soap_instantiate_ns1__Modulo_USCOREobtener_USCOREhora(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline void soap_delete_ns1__Modulo_USCOREobtener_USCOREhora(struct soap *soap, ns1__Modulo_USCOREobtener_USCOREhora *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso_ns1__Modulo_USCOREAsistenciaResponse
#define SOAP_TYPE_acceso_ns1__Modulo_USCOREAsistenciaResponse (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Modulo_USCOREAsistenciaResponse(struct soap*, const char*, int, const ns1__Modulo_USCOREAsistenciaResponse *, const char*);
SOAP_FMAC3 ns1__Modulo_USCOREAsistenciaResponse * SOAP_FMAC4 soap_in_ns1__Modulo_USCOREAsistenciaResponse(struct soap*, const char*, ns1__Modulo_USCOREAsistenciaResponse *, const char*);

#ifndef soap_write_ns1__Modulo_USCOREAsistenciaResponse
#define soap_write_ns1__Modulo_USCOREAsistenciaResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:Modulo_AsistenciaResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__Modulo_USCOREAsistenciaResponse * SOAP_FMAC4 soap_get_ns1__Modulo_USCOREAsistenciaResponse(struct soap*, ns1__Modulo_USCOREAsistenciaResponse *, const char*, const char*);

#ifndef soap_read_ns1__Modulo_USCOREAsistenciaResponse
#define soap_read_ns1__Modulo_USCOREAsistenciaResponse(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_ns1__Modulo_USCOREAsistenciaResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__Modulo_USCOREAsistenciaResponse * SOAP_FMAC2 soap_instantiate_ns1__Modulo_USCOREAsistenciaResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__Modulo_USCOREAsistenciaResponse * soap_new_ns1__Modulo_USCOREAsistenciaResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__Modulo_USCOREAsistenciaResponse(soap, n, NULL, NULL, NULL); }

inline ns1__Modulo_USCOREAsistenciaResponse * soap_new_req_ns1__Modulo_USCOREAsistenciaResponse(struct soap *soap) { ns1__Modulo_USCOREAsistenciaResponse *_p = soap_instantiate_ns1__Modulo_USCOREAsistenciaResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__Modulo_USCOREAsistenciaResponse * soap_new_set_ns1__Modulo_USCOREAsistenciaResponse(struct soap *soap, std::string *return_) { ns1__Modulo_USCOREAsistenciaResponse *_p = soap_instantiate_ns1__Modulo_USCOREAsistenciaResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__Modulo_USCOREAsistenciaResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__Modulo_USCOREAsistenciaResponse(struct soap *soap, ns1__Modulo_USCOREAsistenciaResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Modulo_USCOREAsistenciaResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso_ns1__Modulo_USCOREAsistencia
#define SOAP_TYPE_acceso_ns1__Modulo_USCOREAsistencia (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Modulo_USCOREAsistencia(struct soap*, const char*, int, const ns1__Modulo_USCOREAsistencia *, const char*);
SOAP_FMAC3 ns1__Modulo_USCOREAsistencia * SOAP_FMAC4 soap_in_ns1__Modulo_USCOREAsistencia(struct soap*, const char*, ns1__Modulo_USCOREAsistencia *, const char*);

#ifndef soap_write_ns1__Modulo_USCOREAsistencia
#define soap_write_ns1__Modulo_USCOREAsistencia(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:Modulo_Asistencia", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__Modulo_USCOREAsistencia * SOAP_FMAC4 soap_get_ns1__Modulo_USCOREAsistencia(struct soap*, ns1__Modulo_USCOREAsistencia *, const char*, const char*);

#ifndef soap_read_ns1__Modulo_USCOREAsistencia
#define soap_read_ns1__Modulo_USCOREAsistencia(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_ns1__Modulo_USCOREAsistencia(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__Modulo_USCOREAsistencia * SOAP_FMAC2 soap_instantiate_ns1__Modulo_USCOREAsistencia(struct soap*, int, const char*, const char*, size_t*);

inline ns1__Modulo_USCOREAsistencia * soap_new_ns1__Modulo_USCOREAsistencia(struct soap *soap, int n = -1) { return soap_instantiate_ns1__Modulo_USCOREAsistencia(soap, n, NULL, NULL, NULL); }

inline ns1__Modulo_USCOREAsistencia * soap_new_req_ns1__Modulo_USCOREAsistencia(struct soap *soap, int tipomarca) { ns1__Modulo_USCOREAsistencia *_p = soap_instantiate_ns1__Modulo_USCOREAsistencia(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__Modulo_USCOREAsistencia::tipomarca = tipomarca; } return _p; }

inline ns1__Modulo_USCOREAsistencia * soap_new_set_ns1__Modulo_USCOREAsistencia(struct soap *soap, std::string *rut, std::string *dato_USCORErecibido, std::string *hash_USCOREalternativo, time_t *fecha, std::string *numerodispositivo, int tipomarca, xsd__base64Binary *foto) { ns1__Modulo_USCOREAsistencia *_p = soap_instantiate_ns1__Modulo_USCOREAsistencia(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__Modulo_USCOREAsistencia::rut = rut; _p->ns1__Modulo_USCOREAsistencia::dato_USCORErecibido = dato_USCORErecibido; _p->ns1__Modulo_USCOREAsistencia::hash_USCOREalternativo = hash_USCOREalternativo; _p->ns1__Modulo_USCOREAsistencia::fecha = fecha; _p->ns1__Modulo_USCOREAsistencia::numerodispositivo = numerodispositivo; _p->ns1__Modulo_USCOREAsistencia::tipomarca = tipomarca; _p->ns1__Modulo_USCOREAsistencia::foto = foto; } return _p; }

inline void soap_delete_ns1__Modulo_USCOREAsistencia(struct soap *soap, ns1__Modulo_USCOREAsistencia *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Modulo_USCOREAsistencia(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso_xsd__base64Binary
#define SOAP_TYPE_acceso_xsd__base64Binary (8)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const xsd__base64Binary *, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, xsd__base64Binary *, const char*);

#ifndef soap_write_xsd__base64Binary
#define soap_write_xsd__base64Binary(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "xsd:base64Binary", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, xsd__base64Binary *, const char*, const char*);

#ifndef soap_read_xsd__base64Binary
#define soap_read_xsd__base64Binary(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_xsd__base64Binary(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 xsd__base64Binary * SOAP_FMAC2 soap_instantiate_xsd__base64Binary(struct soap*, int, const char*, const char*, size_t*);

inline xsd__base64Binary * soap_new_xsd__base64Binary(struct soap *soap, int n = -1) { return soap_instantiate_xsd__base64Binary(soap, n, NULL, NULL, NULL); }

inline xsd__base64Binary * soap_new_req_xsd__base64Binary(struct soap *soap) { xsd__base64Binary *_p = soap_instantiate_xsd__base64Binary(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline xsd__base64Binary * soap_new_set_xsd__base64Binary(struct soap *soap, unsigned char *__ptr, int __size, char *id, char *type, char *options) { xsd__base64Binary *_p = soap_instantiate_xsd__base64Binary(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->xsd__base64Binary::__ptr = __ptr; _p->xsd__base64Binary::__size = __size; _p->xsd__base64Binary::id = id; _p->xsd__base64Binary::type = type; _p->xsd__base64Binary::options = options; } return _p; }

inline void soap_delete_xsd__base64Binary(struct soap *soap, xsd__base64Binary *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__base64Binary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_acceso_SOAP_ENV__Fault
#define SOAP_TYPE_acceso_SOAP_ENV__Fault (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_SOAP_ENV__Fault(soap, data),0) || acceso::soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_acceso_SOAP_ENV__Reason
#define SOAP_TYPE_acceso_SOAP_ENV__Reason (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_SOAP_ENV__Reason(soap, data),0) || acceso::soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_acceso_SOAP_ENV__Detail
#define SOAP_TYPE_acceso_SOAP_ENV__Detail (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_SOAP_ENV__Detail(soap, data),0) || acceso::soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_acceso_SOAP_ENV__Code
#define SOAP_TYPE_acceso_SOAP_ENV__Code (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_SOAP_ENV__Code(soap, data),0) || acceso::soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_acceso_SOAP_ENV__Header
#define SOAP_TYPE_acceso_SOAP_ENV__Header (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_SOAP_ENV__Header(soap, data),0) || acceso::soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_acceso___ns1__Modulo_USCOREAsistencia
#define SOAP_TYPE_acceso___ns1__Modulo_USCOREAsistencia (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Modulo_USCOREAsistencia(struct soap*, struct __ns1__Modulo_USCOREAsistencia *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Modulo_USCOREAsistencia(struct soap*, const struct __ns1__Modulo_USCOREAsistencia *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Modulo_USCOREAsistencia(struct soap*, const char*, int, const struct __ns1__Modulo_USCOREAsistencia *, const char*);
SOAP_FMAC3 struct __ns1__Modulo_USCOREAsistencia * SOAP_FMAC4 soap_in___ns1__Modulo_USCOREAsistencia(struct soap*, const char*, struct __ns1__Modulo_USCOREAsistencia *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Modulo_USCOREAsistencia(struct soap*, const struct __ns1__Modulo_USCOREAsistencia *, const char*, const char*);

#ifndef soap_write___ns1__Modulo_USCOREAsistencia
#define soap_write___ns1__Modulo_USCOREAsistencia(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize___ns1__Modulo_USCOREAsistencia(soap, data),0) || acceso::soap_put___ns1__Modulo_USCOREAsistencia(soap, data, "-ns1:Modulo_Asistencia", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Modulo_USCOREAsistencia * SOAP_FMAC4 soap_get___ns1__Modulo_USCOREAsistencia(struct soap*, struct __ns1__Modulo_USCOREAsistencia *, const char*, const char*);

#ifndef soap_read___ns1__Modulo_USCOREAsistencia
#define soap_read___ns1__Modulo_USCOREAsistencia(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get___ns1__Modulo_USCOREAsistencia(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Modulo_USCOREAsistencia * SOAP_FMAC2 soap_instantiate___ns1__Modulo_USCOREAsistencia(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Modulo_USCOREAsistencia * soap_new___ns1__Modulo_USCOREAsistencia(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Modulo_USCOREAsistencia(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Modulo_USCOREAsistencia * soap_new_req___ns1__Modulo_USCOREAsistencia(struct soap *soap) { struct __ns1__Modulo_USCOREAsistencia *_p = soap_instantiate___ns1__Modulo_USCOREAsistencia(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Modulo_USCOREAsistencia(soap, _p); } return _p; }

inline struct __ns1__Modulo_USCOREAsistencia * soap_new_set___ns1__Modulo_USCOREAsistencia(struct soap *soap, ns1__Modulo_USCOREAsistencia *ns1__Modulo_USCOREAsistencia_) { struct __ns1__Modulo_USCOREAsistencia *_p = soap_instantiate___ns1__Modulo_USCOREAsistencia(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Modulo_USCOREAsistencia(soap, _p); _p->ns1__Modulo_USCOREAsistencia_ = ns1__Modulo_USCOREAsistencia_; } return _p; }

inline void soap_delete___ns1__Modulo_USCOREAsistencia(struct soap *soap, struct __ns1__Modulo_USCOREAsistencia *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Modulo_USCOREAsistencia(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso___ns1__Modulo_USCOREobtener_USCOREhora
#define SOAP_TYPE_acceso___ns1__Modulo_USCOREobtener_USCOREhora (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, struct __ns1__Modulo_USCOREobtener_USCOREhora *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, const struct __ns1__Modulo_USCOREobtener_USCOREhora *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, const char*, int, const struct __ns1__Modulo_USCOREobtener_USCOREhora *, const char*);
SOAP_FMAC3 struct __ns1__Modulo_USCOREobtener_USCOREhora * SOAP_FMAC4 soap_in___ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, const char*, struct __ns1__Modulo_USCOREobtener_USCOREhora *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, const struct __ns1__Modulo_USCOREobtener_USCOREhora *, const char*, const char*);

#ifndef soap_write___ns1__Modulo_USCOREobtener_USCOREhora
#define soap_write___ns1__Modulo_USCOREobtener_USCOREhora(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize___ns1__Modulo_USCOREobtener_USCOREhora(soap, data),0) || acceso::soap_put___ns1__Modulo_USCOREobtener_USCOREhora(soap, data, "-ns1:Modulo_obtener_hora", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Modulo_USCOREobtener_USCOREhora * SOAP_FMAC4 soap_get___ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, struct __ns1__Modulo_USCOREobtener_USCOREhora *, const char*, const char*);

#ifndef soap_read___ns1__Modulo_USCOREobtener_USCOREhora
#define soap_read___ns1__Modulo_USCOREobtener_USCOREhora(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get___ns1__Modulo_USCOREobtener_USCOREhora(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Modulo_USCOREobtener_USCOREhora * SOAP_FMAC2 soap_instantiate___ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Modulo_USCOREobtener_USCOREhora * soap_new___ns1__Modulo_USCOREobtener_USCOREhora(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Modulo_USCOREobtener_USCOREhora(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Modulo_USCOREobtener_USCOREhora * soap_new_req___ns1__Modulo_USCOREobtener_USCOREhora(struct soap *soap) { struct __ns1__Modulo_USCOREobtener_USCOREhora *_p = soap_instantiate___ns1__Modulo_USCOREobtener_USCOREhora(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Modulo_USCOREobtener_USCOREhora(soap, _p); } return _p; }

inline struct __ns1__Modulo_USCOREobtener_USCOREhora * soap_new_set___ns1__Modulo_USCOREobtener_USCOREhora(struct soap *soap, ns1__Modulo_USCOREobtener_USCOREhora *ns1__Modulo_USCOREobtener_USCOREhora_) { struct __ns1__Modulo_USCOREobtener_USCOREhora *_p = soap_instantiate___ns1__Modulo_USCOREobtener_USCOREhora(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Modulo_USCOREobtener_USCOREhora(soap, _p); _p->ns1__Modulo_USCOREobtener_USCOREhora_ = ns1__Modulo_USCOREobtener_USCOREhora_; } return _p; }

inline void soap_delete___ns1__Modulo_USCOREobtener_USCOREhora(struct soap *soap, struct __ns1__Modulo_USCOREobtener_USCOREhora *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Modulo_USCOREobtener_USCOREhora(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_acceso___ns1__Modulo_USCOREAcceso_USCOREPuerta
#define SOAP_TYPE_acceso___ns1__Modulo_USCOREAcceso_USCOREPuerta (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, struct __ns1__Modulo_USCOREAcceso_USCOREPuerta *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, const struct __ns1__Modulo_USCOREAcceso_USCOREPuerta *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, const char*, int, const struct __ns1__Modulo_USCOREAcceso_USCOREPuerta *, const char*);
SOAP_FMAC3 struct __ns1__Modulo_USCOREAcceso_USCOREPuerta * SOAP_FMAC4 soap_in___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, const char*, struct __ns1__Modulo_USCOREAcceso_USCOREPuerta *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, const struct __ns1__Modulo_USCOREAcceso_USCOREPuerta *, const char*, const char*);

#ifndef soap_write___ns1__Modulo_USCOREAcceso_USCOREPuerta
#define soap_write___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, data),0) || acceso::soap_put___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, data, "-ns1:Modulo_Acceso_Puerta", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Modulo_USCOREAcceso_USCOREPuerta * SOAP_FMAC4 soap_get___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, struct __ns1__Modulo_USCOREAcceso_USCOREPuerta *, const char*, const char*);

#ifndef soap_read___ns1__Modulo_USCOREAcceso_USCOREPuerta
#define soap_read___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Modulo_USCOREAcceso_USCOREPuerta * SOAP_FMAC2 soap_instantiate___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Modulo_USCOREAcceso_USCOREPuerta * soap_new___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Modulo_USCOREAcceso_USCOREPuerta * soap_new_req___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap *soap) { struct __ns1__Modulo_USCOREAcceso_USCOREPuerta *_p = soap_instantiate___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, _p); } return _p; }

inline struct __ns1__Modulo_USCOREAcceso_USCOREPuerta * soap_new_set___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap *soap, ns1__Modulo_USCOREAcceso_USCOREPuerta *ns1__Modulo_USCOREAcceso_USCOREPuerta_) { struct __ns1__Modulo_USCOREAcceso_USCOREPuerta *_p = soap_instantiate___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Modulo_USCOREAcceso_USCOREPuerta(soap, _p); _p->ns1__Modulo_USCOREAcceso_USCOREPuerta_ = ns1__Modulo_USCOREAcceso_USCOREPuerta_; } return _p; }

inline void soap_delete___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap *soap, struct __ns1__Modulo_USCOREAcceso_USCOREPuerta *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_acceso_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_acceso_PointerToSOAP_ENV__Reason (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || acceso::soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_acceso_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_acceso_PointerToSOAP_ENV__Detail (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || acceso::soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_acceso_PointerToSOAP_ENV__Code
#define SOAP_TYPE_acceso_PointerToSOAP_ENV__Code (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || acceso::soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_acceso_PointerTons1__Modulo_USCOREAsistencia
#define SOAP_TYPE_acceso_PointerTons1__Modulo_USCOREAsistencia (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Modulo_USCOREAsistencia(struct soap*, ns1__Modulo_USCOREAsistencia *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Modulo_USCOREAsistencia(struct soap*, const char *, int, ns1__Modulo_USCOREAsistencia *const*, const char *);
SOAP_FMAC3 ns1__Modulo_USCOREAsistencia ** SOAP_FMAC4 soap_in_PointerTons1__Modulo_USCOREAsistencia(struct soap*, const char*, ns1__Modulo_USCOREAsistencia **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Modulo_USCOREAsistencia(struct soap*, ns1__Modulo_USCOREAsistencia *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__Modulo_USCOREAsistencia
#define soap_write_PointerTons1__Modulo_USCOREAsistencia(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerTons1__Modulo_USCOREAsistencia(soap, data),0) || acceso::soap_put_PointerTons1__Modulo_USCOREAsistencia(soap, data, "ns1:Modulo_Asistencia", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__Modulo_USCOREAsistencia ** SOAP_FMAC4 soap_get_PointerTons1__Modulo_USCOREAsistencia(struct soap*, ns1__Modulo_USCOREAsistencia **, const char*, const char*);

#ifndef soap_read_PointerTons1__Modulo_USCOREAsistencia
#define soap_read_PointerTons1__Modulo_USCOREAsistencia(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerTons1__Modulo_USCOREAsistencia(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_PointerTons1__Modulo_USCOREobtener_USCOREhora
#define SOAP_TYPE_acceso_PointerTons1__Modulo_USCOREobtener_USCOREhora (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Modulo_USCOREobtener_USCOREhora(struct soap*, ns1__Modulo_USCOREobtener_USCOREhora *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Modulo_USCOREobtener_USCOREhora(struct soap*, const char *, int, ns1__Modulo_USCOREobtener_USCOREhora *const*, const char *);
SOAP_FMAC3 ns1__Modulo_USCOREobtener_USCOREhora ** SOAP_FMAC4 soap_in_PointerTons1__Modulo_USCOREobtener_USCOREhora(struct soap*, const char*, ns1__Modulo_USCOREobtener_USCOREhora **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Modulo_USCOREobtener_USCOREhora(struct soap*, ns1__Modulo_USCOREobtener_USCOREhora *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__Modulo_USCOREobtener_USCOREhora
#define soap_write_PointerTons1__Modulo_USCOREobtener_USCOREhora(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerTons1__Modulo_USCOREobtener_USCOREhora(soap, data),0) || acceso::soap_put_PointerTons1__Modulo_USCOREobtener_USCOREhora(soap, data, "ns1:Modulo_obtener_hora", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__Modulo_USCOREobtener_USCOREhora ** SOAP_FMAC4 soap_get_PointerTons1__Modulo_USCOREobtener_USCOREhora(struct soap*, ns1__Modulo_USCOREobtener_USCOREhora **, const char*, const char*);

#ifndef soap_read_PointerTons1__Modulo_USCOREobtener_USCOREhora
#define soap_read_PointerTons1__Modulo_USCOREobtener_USCOREhora(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerTons1__Modulo_USCOREobtener_USCOREhora(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta
#define SOAP_TYPE_acceso_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, ns1__Modulo_USCOREAcceso_USCOREPuerta *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, const char *, int, ns1__Modulo_USCOREAcceso_USCOREPuerta *const*, const char *);
SOAP_FMAC3 ns1__Modulo_USCOREAcceso_USCOREPuerta ** SOAP_FMAC4 soap_in_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, const char*, ns1__Modulo_USCOREAcceso_USCOREPuerta **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, ns1__Modulo_USCOREAcceso_USCOREPuerta *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta
#define soap_write_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(soap, data),0) || acceso::soap_put_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(soap, data, "ns1:Modulo_Acceso_Puerta", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__Modulo_USCOREAcceso_USCOREPuerta ** SOAP_FMAC4 soap_get_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(struct soap*, ns1__Modulo_USCOREAcceso_USCOREPuerta **, const char*, const char*);

#ifndef soap_read_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta
#define soap_read_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerTons1__Modulo_USCOREAcceso_USCOREPuerta(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_PointerToxsd__base64Binary
#define SOAP_TYPE_acceso_PointerToxsd__base64Binary (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__base64Binary(struct soap*, xsd__base64Binary *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__base64Binary(struct soap*, const char *, int, xsd__base64Binary *const*, const char *);
SOAP_FMAC3 xsd__base64Binary ** SOAP_FMAC4 soap_in_PointerToxsd__base64Binary(struct soap*, const char*, xsd__base64Binary **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__base64Binary(struct soap*, xsd__base64Binary *const*, const char*, const char*);

#ifndef soap_write_PointerToxsd__base64Binary
#define soap_write_PointerToxsd__base64Binary(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerToxsd__base64Binary(soap, data),0) || acceso::soap_put_PointerToxsd__base64Binary(soap, data, "xsd:base64Binary", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 xsd__base64Binary ** SOAP_FMAC4 soap_get_PointerToxsd__base64Binary(struct soap*, xsd__base64Binary **, const char*, const char*);

#ifndef soap_read_PointerToxsd__base64Binary
#define soap_read_PointerToxsd__base64Binary(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerToxsd__base64Binary(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_PointerTotime
#define SOAP_TYPE_acceso_PointerTotime (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotime(struct soap*, time_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotime(struct soap*, const char *, int, time_t *const*, const char *);
SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_in_PointerTotime(struct soap*, const char*, time_t **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotime(struct soap*, time_t *const*, const char*, const char*);

#ifndef soap_write_PointerTotime
#define soap_write_PointerTotime(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerTotime(soap, data),0) || acceso::soap_put_PointerTotime(soap, data, "dateTime", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_get_PointerTotime(struct soap*, time_t **, const char*, const char*);

#ifndef soap_read_PointerTotime
#define soap_read_PointerTotime(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerTotime(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_PointerTostd__string
#define SOAP_TYPE_acceso_PointerTostd__string (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerTostd__string(soap, data),0) || acceso::soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_PointerTounsignedByte
#define SOAP_TYPE_acceso_PointerTounsignedByte (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);

#ifndef soap_write_PointerTounsignedByte
#define soap_write_PointerTounsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_PointerTounsignedByte(soap, data),0) || acceso::soap_put_PointerTounsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);

#ifndef soap_read_PointerTounsignedByte
#define soap_read_PointerTounsignedByte(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_PointerTounsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso__QName
#define SOAP_TYPE_acceso__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize__QName(soap, data),0) || acceso::soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_acceso_string
#define SOAP_TYPE_acceso_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (acceso::soap_serialize_string(soap, data),0) || acceso::soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !acceso::soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


} // namespace acceso


#endif

/* End of accesoH.h */
