/* fotoClient.cpp
   Generated by gSOAP 2.8.21 from foto.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "fotoH.h"

namespace foto {

SOAP_SOURCE_STAMP("@(#) fotoClient.cpp ver 2.8.21 2015-04-01 05:48:00 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___foto1__obtenerFoto(struct soap *soap, const char *soap_endpoint, const char *soap_action, foto1__obtenerFoto *foto1__obtenerFoto_, foto1__obtenerFotoResponse &foto1__obtenerFotoResponse_)
{	struct __foto1__obtenerFoto soap_tmp___foto1__obtenerFoto;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://webservices.utfsm.cl:80/WS_FOTOS/FotosWS";
	if (soap_action == NULL)
		soap_action = "http://fotos.cl.usm.org/FotosWS/obtenerFotoRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___foto1__obtenerFoto.foto1__obtenerFoto_ = foto1__obtenerFoto_;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___foto1__obtenerFoto(soap, &soap_tmp___foto1__obtenerFoto);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___foto1__obtenerFoto(soap, &soap_tmp___foto1__obtenerFoto, "-foto1:obtenerFoto", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___foto1__obtenerFoto(soap, &soap_tmp___foto1__obtenerFoto, "-foto1:obtenerFoto", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&foto1__obtenerFotoResponse_)
		return soap_closesock(soap);
	foto1__obtenerFotoResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	foto1__obtenerFotoResponse_.soap_get(soap, "foto1:obtenerFotoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

} // namespace foto


#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of fotoClient.cpp */
