/* casinoClient.cpp
   Generated by gSOAP 2.8.21 from casino.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "casinoH.h"

namespace casino {

SOAP_SOURCE_STAMP("@(#) casinoClient.cpp ver 2.8.21 2015-06-05 17:59:26 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___casino1__Modulo_USCOREAcceso_USCOREPuerta(struct soap *soap, const char *soap_endpoint, const char *soap_action, casino1__Modulo_USCOREAcceso_USCOREPuerta *casino1__Modulo_USCOREAcceso_USCOREPuerta_, casino1__Modulo_USCOREAcceso_USCOREPuertaResponse &casino1__Modulo_USCOREAcceso_USCOREPuertaResponse_)
{	struct __casino1__Modulo_USCOREAcceso_USCOREPuerta soap_tmp___casino1__Modulo_USCOREAcceso_USCOREPuerta;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ssodes.usm.cl:80/Ws_ControlAcceso/Ws_Principal";
	if (soap_action == NULL)
		soap_action = "http://Principal/Ws_Principal/Modulo_Acceso_PuertaRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___casino1__Modulo_USCOREAcceso_USCOREPuerta.casino1__Modulo_USCOREAcceso_USCOREPuerta_ = casino1__Modulo_USCOREAcceso_USCOREPuerta_;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___casino1__Modulo_USCOREAcceso_USCOREPuerta(soap, &soap_tmp___casino1__Modulo_USCOREAcceso_USCOREPuerta);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___casino1__Modulo_USCOREAcceso_USCOREPuerta(soap, &soap_tmp___casino1__Modulo_USCOREAcceso_USCOREPuerta, "-casino1:Modulo_Acceso_Puerta", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___casino1__Modulo_USCOREAcceso_USCOREPuerta(soap, &soap_tmp___casino1__Modulo_USCOREAcceso_USCOREPuerta, "-casino1:Modulo_Acceso_Puerta", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&casino1__Modulo_USCOREAcceso_USCOREPuertaResponse_)
		return soap_closesock(soap);
	casino1__Modulo_USCOREAcceso_USCOREPuertaResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	casino1__Modulo_USCOREAcceso_USCOREPuertaResponse_.soap_get(soap, "casino1:Modulo_Acceso_PuertaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___casino1__Modulo_USCOREobtener_USCOREhora(struct soap *soap, const char *soap_endpoint, const char *soap_action, casino1__Modulo_USCOREobtener_USCOREhora *casino1__Modulo_USCOREobtener_USCOREhora_, casino1__Modulo_USCOREobtener_USCOREhoraResponse &casino1__Modulo_USCOREobtener_USCOREhoraResponse_)
{	struct __casino1__Modulo_USCOREobtener_USCOREhora soap_tmp___casino1__Modulo_USCOREobtener_USCOREhora;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ssodes.usm.cl:80/Ws_ControlAcceso/Ws_Principal";
	if (soap_action == NULL)
		soap_action = "http://Principal/Ws_Principal/Modulo_obtener_horaRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___casino1__Modulo_USCOREobtener_USCOREhora.casino1__Modulo_USCOREobtener_USCOREhora_ = casino1__Modulo_USCOREobtener_USCOREhora_;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___casino1__Modulo_USCOREobtener_USCOREhora(soap, &soap_tmp___casino1__Modulo_USCOREobtener_USCOREhora);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___casino1__Modulo_USCOREobtener_USCOREhora(soap, &soap_tmp___casino1__Modulo_USCOREobtener_USCOREhora, "-casino1:Modulo_obtener_hora", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___casino1__Modulo_USCOREobtener_USCOREhora(soap, &soap_tmp___casino1__Modulo_USCOREobtener_USCOREhora, "-casino1:Modulo_obtener_hora", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&casino1__Modulo_USCOREobtener_USCOREhoraResponse_)
		return soap_closesock(soap);
	casino1__Modulo_USCOREobtener_USCOREhoraResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	casino1__Modulo_USCOREobtener_USCOREhoraResponse_.soap_get(soap, "casino1:Modulo_obtener_horaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___casino1__Modulo_USCOREAsistencia(struct soap *soap, const char *soap_endpoint, const char *soap_action, casino1__Modulo_USCOREAsistencia *casino1__Modulo_USCOREAsistencia_, casino1__Modulo_USCOREAsistenciaResponse &casino1__Modulo_USCOREAsistenciaResponse_)
{	struct __casino1__Modulo_USCOREAsistencia soap_tmp___casino1__Modulo_USCOREAsistencia;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ssodes.usm.cl:80/Ws_ControlAcceso/Ws_Principal";
	if (soap_action == NULL)
		soap_action = "http://Principal/Ws_Principal/Modulo_AsistenciaRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___casino1__Modulo_USCOREAsistencia.casino1__Modulo_USCOREAsistencia_ = casino1__Modulo_USCOREAsistencia_;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___casino1__Modulo_USCOREAsistencia(soap, &soap_tmp___casino1__Modulo_USCOREAsistencia);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___casino1__Modulo_USCOREAsistencia(soap, &soap_tmp___casino1__Modulo_USCOREAsistencia, "-casino1:Modulo_Asistencia", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___casino1__Modulo_USCOREAsistencia(soap, &soap_tmp___casino1__Modulo_USCOREAsistencia, "-casino1:Modulo_Asistencia", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&casino1__Modulo_USCOREAsistenciaResponse_)
		return soap_closesock(soap);
	casino1__Modulo_USCOREAsistenciaResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	casino1__Modulo_USCOREAsistenciaResponse_.soap_get(soap, "casino1:Modulo_AsistenciaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___casino1__Modulo_USCORECasino(struct soap *soap, const char *soap_endpoint, const char *soap_action, casino1__Modulo_USCORECasino *casino1__Modulo_USCORECasino_, casino1__Modulo_USCORECasinoResponse &casino1__Modulo_USCORECasinoResponse_)
{	struct __casino1__Modulo_USCORECasino soap_tmp___casino1__Modulo_USCORECasino;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://ssodes.usm.cl:80/Ws_ControlAcceso/Ws_Principal";
	if (soap_action == NULL)
		soap_action = "http://Principal/Ws_Principal/Modulo_CasinoRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___casino1__Modulo_USCORECasino.casino1__Modulo_USCORECasino_ = casino1__Modulo_USCORECasino_;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___casino1__Modulo_USCORECasino(soap, &soap_tmp___casino1__Modulo_USCORECasino);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___casino1__Modulo_USCORECasino(soap, &soap_tmp___casino1__Modulo_USCORECasino, "-casino1:Modulo_Casino", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___casino1__Modulo_USCORECasino(soap, &soap_tmp___casino1__Modulo_USCORECasino, "-casino1:Modulo_Casino", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&casino1__Modulo_USCORECasinoResponse_)
		return soap_closesock(soap);
	casino1__Modulo_USCORECasinoResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	casino1__Modulo_USCORECasinoResponse_.soap_get(soap, "casino1:Modulo_CasinoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

} // namespace casino


#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of casinoClient.cpp */
